version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_test
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27019:27017"
    volumes:
      - mongo-data-test:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_test
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb_test
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin 
      ME_CONFIG_BASICAUTH_USERNAME: PM929
      ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - "8084:8081"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"

  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "8001:8001"

volumes:
  mongo-data-test:
    driver: local
